name: Meyappan Subbaiah
url: 'https://meysubb.github.io'
description: Meyappan

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'Meyappan'
disqus_shortname: msubbaiah
google_analytics: UA-42209870-1

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed

google_analytics: UA-90700102-1
